const quotes = [
    // amelia quotes (22)
    "everything that is ballshaped will be consumed \n\n--amelia\n",
    "NATALIE do not eat dilators\n\n--amelia\n",
    "the tattoo could just end up being up ur pussy \n\n--amelia\n",
    "like just a pile of boobs \n\n--amelia\n",
    "like can human bodies even DIGEST fetuses \n\n--amelia\n",
    "i didnt know wanting boobs can kill the entirety of europe \n\n--amelia\n",
    "i guess u just need breeding /j \n\n--amelia\n",
    "(it just releases gocks everywhere) \n\n--amelia\n",
    "thats bc you'd be using this only inside nattie \n\n--amelia\n",
    "the julie does NOT know about my habit of eating kids \n\n--amelia\n",
    "just dont put it in \n\n--amelia\n",
    "FOOT SERVER???? [#Unknown] \n\n--amelian\n",
    "bro just invented edible cock \n\n--amelia\n",
    "im going to shit myself \n\n--amelia\n",
    "ok i busted out the foot \n\n--amelia\n",
    "its just pink hole \n\n--amelia\n",
    "MAYBE this head isnt good \n\n--amelia\n",
    "and pussy hair. cant forget pussy hair. \n\n--amelia\n",
    'ig theyd have their dreams of genocide "ruined" by sex \n\n--amelia\n',
    "how would have they uh \n\n> gotten inside \n\n--amelia\n",
    "pussy time :3c \n\n--amelia\n",
    "brb gonna shit myself /hj \n\n--amelia\n",
    "lets stick lemons in piss \n\n--amelia\n",

    // natalie quotes (4)
    "i did NOT expect to be talking abt blending stolen fetuses today \n\n--natalie\n",
    "wait wtf why are there like holes \n\n--natalie\n",
    "129 insertions(+) :weary: \n\n--natalie\n",
    "i mean he had a fkn glass jar pop inside his ass and he didnt even SAY anything \n\n--natalie\n",
];

const jennQuotes = [
    // jenn quotes (114)
    "oh no its's 9/11",
    "i bet striders NEVER skip leg day",
    "Saige Saigfe Sasige Sausage",
    "put your balls in my mouth like its boba tea",
    "i havnt been breeding a lot bc ive been busy",
    "Step on me, froggy",
    "He's going to fuck the chicken",
    "the way to my heart is your chest",
    "not im hyperfocused on hole",
    "I've been having fun",
    "these wither skeles need to give me more head",
    "thanks for head",
    "64 head",
    "Thank you for pissing on me",
    "Jennussy",
    "cloacussy",
    "I was subjected to Dutch!",
    "alright I'm in",
    "i named my shit after ppl on the server",
    "I have shulkers of fuck to throw at her",
    "Get your stereotypes right you ungrateful little cunt.",
    "its still a lil rough",
    "fuck Dolores O'Riordan",
    "there was whole ass dick in there",
    "i feel so naked with no mods",
    "poop",
    "I shower naked",
    "I'm eating wren's pork. . .Wren porked me and i've been eating it ever since.",
    "tits very good",
    "Jenn why is it so small?",
    "you blow yourself?",
    "ITS JUST A SHAFT AND HEAD!! NO BALLS!!",
    "yeah i mainly need help gettin the juice flowin",
    "And I love recieving!",
    "like fuck i want to eat magenta concrete powder",
    "Oh no Jaiden your huffing paint!",
    "They're so big!",
    "They're so massive!",
    "gonna suck ass",
    "if you fade away how can you suck on my titties",
    "I go on top everytime",
    "kyle let's touch tips",
    "the submissive and breedable update",
    "I will build you a porch to shit on",
    "It will still be steamy",
    "itll still be steaming",
    "Nice cock",
    "i love eating skin",
    "im gonna lick your toes",
    "trim me mommy",
    "no im suckin the grippers",
    "Queen Lizzy blew your back out?",
    "dont worry ive repaired your mother",
    "Girlcock is still my favorite horse ive seen on the server",
    "FEET",
    "Jesus can suck my fat cock, limited time offer",
    "Ogranic cock",
    "HAVE YOU CHECKED YOUR BUTTHOLE",
    "Sluts are not allowed full stop.",
    "I like to think that the avocado is autistic",
    "I'm gonna conc your crete.",
    "Reject women. Embrace hole.",
    "and i fucked your pots im sorry",
    "Just cracked me neck and it felt so good i think i just nutted",
    "im dummy thicc and the clap of my ass cheeks makes stealth impossible",
    "im so thicc my thighs thunder when i walk",
    "im actually about to exit my big cock era",
    "bouta enter my puffy pussy era",
    "you KNOW im hittin that bong like its a child",
    "I hate it when I leak purple",
    "its fun to pull it out if someone is being mean while im femme af",
    "I'll get one while I'm getting my dick peeled open",
    "I guess science here is getting my balls",
    "Oh Skylar - hit them with your sausage",
    "I didn't expect you to go in!",
    "eat my ass",
    "I'm also autistic over Halo",
    "In space no one can hear you commit war crimes",
    "I've hit new levels of deranged",
    "I need those to buy head",
    "It's my favorite pastime - getting dysentery",
    "Pussy stank like corn chips",
    "Source: I'm ripping ass",
    "Socks are for lovers",
    "I bonemeal my chest fr fr",
    "puwunish me",
    "OMG. I sell my piss to strangers on the internet #girlboss",
    "oh lets go to the dicks",
    "my titty milk is 50% microplastics",
    "What if we kissed webcams",
    "is this about pubic farts",
    "otherwise ive just been massaging it when im in the shower",
    "he walks in and my pants are already off",
    "she scoobys on my dooby till i doo",
    "martin can you please get your pork out of my face",
    "I don't like doing things cuff of the moment.",
    "im rippin ass as we speak",
    '"Fuck you" -Skylar | "please do" -Jenn',
    "im about to hit the first tower",
    "i am Jennyafer; first of my name, dsetroyer of penis",
    "I'm so full of microplastics.",
    "i lose mine to my gambling addiction and monthly head",
    "Yeah one sex",
    "I love cock",
    "war crimes are badass",
    "momma needs her cummies monster",
    "I'd fuck my lungs",
    "Tuna COME now!",
    "I have a thing for British twinks..... and Alastair",
    "im drinking what ur blasting",
    "NO I CIRCUMSIZED MY LAVALAMP",
    "cum cum cum cum cum. CUM NOW",
    "ill moan even louder then",
];

const natalieQuotes = [
    "'dont eat poopoo' literally 1984",
    "the hole",
    "hes bouncin off my booty cheeks i love the way he rides",
    "i should not be trusted with pumpkins",
    "idk how to get into your hole",
    "the potatoes are made from human flesh dw",
    "im gonna eat the flex tape",
    "meow",
    "cock if it was good",
    "i am now inside lenin",
    "lenin just gave birth to me",
    "welcome to lenin's ass",
    "welcome back whore",
    "do not fuck the numbers",
    "got negative ass, shits concave",
    "is this vulva city-themed",
    "i lost my rod again",
    "'onceler sexy hot onceler booty gif'",
    "do the cat >:)",
    "can the placing of the boobs wait a little bit",
    `"maybe if i twist hard enough itll come off" *leaves*`,
    "u wouldnt dare give the town top surgery",
    "im not sure what u expect me to do with all this cake",
    "and i literally invented planet vore",
    "u already paid me for the feet",
    "honestly id feel naked without my cat ears",
    "im not cis im normal",
];

const ameliaQuotes = [
    "we will unenglishify her",
    "DO NOT HAVE SEX WITH YOUR BLAHAJ",
    "how does it feel to be inside a sniffer",
    "the full thing is out now",
    "this thing is so big",
    "my boobs just jumped out of my torso",
    "replace the us gov w boobs",
    "summer is fucking",
    "i cant believe we're inside a sniffer",
    "actually which ones bigger",
    "ok i have now shit myself",
    "we are *not* going to keep boners in sas",
    "stasen is weird tho",
    "meow",
    "as soon as i get my pc built i will literally download BG3 and shart",
    "new rule you cant use screenshots in the oocqc thread because they take too much time",
    "please kindly head on over to the nearest public park and then explode",
    "context would be *highly* appreciated",
    "no cassi im autistic",
    "semi-automatic penis",
    "either way its too long",
    "gonna shit myself rn dish",

    "(it just releases gocks everywhere)",
    "thats bc you'd be using this only inside nattie",
    "and pussy hair. cant forget pussy hair.",
    "pussy time :3c",
];

module.exports = {
    quotes,
    jennQuotes,
    natalieQuotes,
    ameliaQuotes,
};
